
export const JWT_PUBLIC_KEY = process.env.JWT_PUBLIC_KEY || `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGfNOQcj8Ki3NYKJqZw7
cNN8yo9NLaBnnz9u7fuFVuPAPyvx39A/aIPF+/Enohgyvk4mR3vo9yBX1yHlGxho
qU2BI3ExkTDGlIUIct1hHtIwy8XtNX3aeAQHOyYWqDY3LylUtyjGjVWE4L2PvWFp
x5xEHmCyhhoI/MD2rHI8lvNmki9Adlt0Hq/2tc8naGLapYWwfnLG+HfX9beUHitV
PTgCA6TPifIrosO+0rxM5BpN+FaE5CsA/DmeN+KO+Kb3yXmfFovaf7HiYSQviODm
YiqX4lS90Y9qbIDbJwt4ZJ82PP3aaruyjiGxg7St8GAGOqA2OpzeTrjEyJjJzFkG
mQIDAQAB
-----END PUBLIC KEY-----
` ;